// <auto-generated />
namespace UnivertsyManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class academician_prop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(academician_prop));
        
        string IMigrationMetadata.Id
        {
            get { return "202309051920001_academician_prop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
